### ISSUE TITLE
Bool Error

### ISSUE THREAD

**Issue by dtrinib** [Dosk3n/Tautulli_IP_Enforcer#2]
Hi,

First I want to thank you for creating this feature and I can't wait to get it working.
I installed this on Centos 7 container within Proxmox appliance.

When I start the service and check the status I get the following error related to TypeError: 'bool' object is not subscriptable

Online says it's related to data type being passed not being of boolean type.

Output:
[root@tautu Tautulli_IP_Enforcer]# systemctl status tautulliipenforcer.service
● tautulliipenforcer.service - Tautulli IP Enforcer Service
   Loaded: loaded (/etc/systemd/system/tautulliipenforcer.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2020-11-10 17:01:30 EST; 23min ago
 Main PID: 2167 (bash)
   CGroup: /system.slice/tautulliipenforcer.service
           ├─2167 /bin/bash /opt/Tautulli/Tautulli_IP_Enforcer/tautulliIpEnforcer.sh
           └─2678 sleep 10

Nov 10 17:24:25 tautu bash[2167]: Sleeping...
Nov 10 17:24:35 tautu bash[2167]: TERM environment variable not set.
Nov 10 17:24:35 tautu bash[2167]: Starting Tautulli IP Enforcer
Nov 10 17:24:35 tautu bash[2167]: Traceback (most recent call last):
Nov 10 17:24:35 tautu bash[2167]: File "tautulliIpEnforcer.py", line 115, in <module>
Nov 10 17:24:35 tautu bash[2167]: Main()
Nov 10 17:24:35 tautu bash[2167]: File "tautulliIpEnforcer.py", line 100, in Main
Nov 10 17:24:35 tautu bash[2167]: if(int(tActivityData["stream_count"]) > 0):
Nov 10 17:24:35 tautu bash[2167]: TypeError: 'bool' object is not subscriptable
Nov 10 17:24:37 tautu bash[2167]: Sleeping...
[root@tautu Tautulli_IP_Enforcer]#

Thanks,

**Comment by dtrinib** [comment]
Hi,

I migrated from Centos 7 to Ubuntu 20.10 (Proxmox CT)
I'm not getting as many errors but there's one when I check the status:
**ModuleNotFoundError: No module named 'requests'**

tat@tat:/opt/Tautulli/Tautulli_IP_Enforcer$ sudo systemctl status tautulliipenforcer.service
* tautulliipenforcer.service - Tautulli IP Enforcer Service
     Loaded: loaded (/etc/systemd/system/tautulliipenforcer.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2021-01-12 13:45:30 EST; 2s ago
   Main PID: 6698 (bash)
      Tasks: 2 (limit: 4915)
     Memory: 784.0K
     CGroup: /system.slice/tautulliipenforcer.service
             |-6698 /bin/bash /opt/Tautulli/Tautulli_IP_Enforcer/tautulliIpEnforcer.sh
             `-6701 sleep 2

Jan 12 13:45:30 tat systemd[1]: Started Tautulli IP Enforcer Service.
Jan 12 13:45:30 tat bash[6699]: TERM environment variable not set.
Jan 12 13:45:30 tat bash[6700]: Traceback (most recent call last):
Jan 12 13:45:30 tat bash[6700]:   File "tautulliIpEnforcer.py", line 1, in <module>
Jan 12 13:45:30 tat bash[6700]:     from TautulliApiHandler import TautulliApiHandler
Jan 12 13:45:30 tat bash[6700]:   File "/opt/Tautulli/Tautulli_IP_Enforcer/TautulliApiHandler.py", line 1, in <module>
Jan 12 13:45:30 tat bash[6700]:     import requests, json
Jan 12 13:45:30 tat bash[6700]: ModuleNotFoundError: No module named 'requests'

**Comment by dtrinib** [comment]
Hi,

I've migrated from Tautulli from Centos 7 to Ubuntu 20.10 (Proxmox CT) and this solved the Python errors and the features works perfectly.

Thanks!
